"""values update

Revision ID: 08f789eb0367
Revises: c18cfbb7d8f5
Create Date: 2023-04-19 23:51:59.851844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08f789eb0367'
down_revision = 'c18cfbb7d8f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
