"""edited user displaying

Revision ID: 5d4ad3cddb27
Revises: cb27ee034cfb
Create Date: 2023-04-09 22:00:41.043069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d4ad3cddb27'
down_revision = 'cb27ee034cfb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
