"""deleted second test user

Revision ID: 79398fe21afd
Revises: 5d4ad3cddb27
Create Date: 2023-04-09 22:02:53.589594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79398fe21afd'
down_revision = '5d4ad3cddb27'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
